### ISSUE TITLE
Repo does not include configure script

### ISSUE THREAD

**Issue by WebbyMD1** [cpptest/cpptest#17]
The git hub repo does not contain the configure script (unlike downloading from the old sourceforge page which does include the configure script).

**Comment by hartwork** [comment]
[Release tarballs](https://github.com/cpptest/cpptest/releases) come with a configure script as they should. Having generated files in version control has always been a bug, not a feature, as generated files get out of sync and pollute diffs.
Please run `./autogen.sh` to generate the configure script in case of a Git clone. Thank you!
