### ISSUE TITLE
Is there a way to force a test to fail after a specified amount of time?

### ISSUE THREAD

**Issue by alocke** [cpptest/cpptest#7]
For example, if you are testing code that hangs, is there a timeout setting?

**Comment by hartwork** [comment]
Hi!

To my best knowledge, you can't really timeout arbitrary code without and extra thread or a fork that you kill. What could be implemented more easily is starting new tests if previous tests have taking up a certain amount of time, already. Without changes of code, using `timeout` of GNU coreutils for running the test suite command could be an option, if your concern is combined execution time. That's all there is right now, I'm afraid.

Best, Sebastian

**Comment by alocke** [comment]
No worries. Thanks!
