### ISSUE TITLE
Issues compiling under GCC 7.30

### ISSUE THREAD

**Issue by reichs** [cpptest/cpptest#9]
Given the level of the C++ standard supported in GCC 7.3.0, there are two issues with the code:
1. std::auto_ptr is deprecated and leads to compile warnings.
2. throw specifications in methods declarations (in test/mytest.cpp) are also deprecated 

I made the following changes to the code:
1. Since I didn't think it would be necessary to share the pointers, I changed all instances of auto_ptr in src/cpptest-suite.h, src/suite.cpp and test/mytest.cpp to unique_ptr
2. I removed the throw specifications from the declarations of func_no_throw() and func_throw_int() in test/mytest.cpp to make it compliant with the current compiler level.

These changes allowed the code to compile and run cleanly.  However, there are two possible issues:
1. I don't know if my assumption about not needing shared pointers is correct.  If not, auto_ptr would need to be changed to shared_ptr.
2. I did not put in any macros to choose between the old code and the new code. 

In addition, there is no documentation in the INSTALL file that one needs to run autogen.sh to build the configure script.

Thanks

S. Reich

**Comment by hartwork** [comment]
Hi @reichs ,

I should mention first that most of the C++ code here is not mine and that I never really got past c++03, so I will need some help understanding some recent C++ things. With that said:

- We could replace `throw()` by `noexcept` and `throw(int)` by `noexcept(false)` — does that sound about right? Would that be better or worse than dropping them altogether?

- Regarding `auto_ptr` and `unique_ptr`: Could you elaborate in the change of semantics if any? If we'd ask 10 C++ people: Would they all recommend `unique_ptr` (if only `std::` is available) or do you consider that a controversial choice? `unique_ptr` is >=C++11 (and `noexcept` as well), right? Let's make configure check for a suitable compiler then.

Best, Sebastian

**Comment by reichs** [comment]
I think that C++ is getting away from placing throw() in the declaration.
Basically, if you put in throw (or noexcept) in templated code you have no
idea what the class provided by the template will do regarding throwing
exceptions.  So, rather than provide some statement about which you know
nothing they are not going to say anything.  In the code that I compiled, I
just dropped the throw clauses totally and it compiled OK.

Regarding auto_ptr, shared_ptr and unique_ptr, it sounds like you aren't up
to what the language people are doing in this area, so I will try to give a
quick background.

The old auto_ptr was basically a ref counted pointer.  In the old C++, if
you returned an auto_ptr from a function then the auto_ptr in the caller
was created by the copy ctor and as a side effect, the ref count was
incremented.  When the function ended, it called the dtor on the auto_ptr
that had been created inside the function and returned to the called.  As a
side effect this decremented the ref count.  The problem that the language
people were trying to deal with is that when you return something like an
int (instead of an object) from a function all that happens is that the
contents get moved from the local (to the function) memory to the caller's
memory.  This move is much more efficient than all this construction and
destruction of objects.  So the language now has something called "move
mode".  You can think of it as a copy ctor that is only called in such
situation.  If you want to implement it you do something like a copy ctor
except that you use a double &&.  So a copy ctor would be MyClass( const
MyClass & old ) and a move ctor would be MyClass( const Myclass && old ).

So, when it comes to auto_ptr there are two situations they wanted to be
able to deal with.  One was to use the new syntax to get rid of the extra
ctor/dtor work by using move mode.  They created a new class called
shared_ptr to do this.  They also wanted to have a ptr class *without* ref
counting.  In order to avoid the problem of two objects pointing at the
same memory (which would eventually call to dtors which would delete the
same memory twice) they created a new class called unique_ptr.  When you
assign one unique_ptr to anothr (or use move mode to copy the contents from
one to the other) then the old unique_ptr is set to null.  IOW, there is
exactly one unique_ptr that points at a particular piece of memory at a
time.

So, getting back to the CppTest code, I think that the auto pointer was
only used to wrap the raw pointer so that the underlying object would get
deleted at the proper time.  There is no need to have multiple pointers to
the same object.  If my analysis was correct then this is really what
unique_ptr is good for.  If I am wrong then the code should use the
share_ptr.

The bigger problem with all of these changes is figuring out when we are
compiling with the old C++ (and using auto_ptr) and when we are compiling
with the new C++.  The GCC libraries have a bunch of preprocessor code
figuring that out in order to mark the code as deprecated.  I really didn't
want to get into that kind of code because I hope to only use new
compilers.  Perhaps the best thing to do is to default to one compiler
standard and just provide a compiler switch manually to allow users to
switch to the other compiler standard.  I don't think anyone wants to be in
the business of maintaining the rules in preprocessor code.

Thanks for following up on this and feel free to contact me about this if
anything isn't clear.

Shalom Reich

**Comment by hartwork** [comment]
Thanks for explaining these details!

I think we need to pick one of these:
- Require >=C++11
  - no need for macros
  - `unique_ptr` everywhere
  - drop `throw (...)`
  - break binary and source compatiblity (and adjust soname accordingly)
- Support both C++03 and >=C++11
  - introduce a macro `UNIQUE_OR_AUTO_PTR` rather than `auto_ptr`/`unique_ptr`
  - hide `throw (...)` from compiler >=C++11 compilers but not C++03 (for ABI compat)
  - pick one out of two sonames in `configure.ac` depending on >=C++11 support
  - keep binary and source compatiblity

Former is cheaper and cleaner and less compatible. I'm okay with either approaches.

**Comment by reichs** [comment]
I think the first approach is better since the new compilers are really
becoming standard for all of the common Linux distributions.  The code is
stable and only needs to change to handle the new compiler.  If there is
someone out there who needs to work with an older compiler they can always
use the older, stable version.  I'm not sure how one could download the old
version since I'm not too knowledgeable about GitHub.  While it would be
possible to tag the old release and use Git to get the tagged release, I'm
not sure what the proper approach is on GitHub.

Shalom

**Comment by hartwork** [comment]
Could you give #10 a closer look?

**Comment by hartwork** [comment]
PS: The soversion bump is based on my best understanding of https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html .

**Comment by reichs** [comment]
Yes.  The API change of the parameter from an auto_ptr to a unique_ptr
constitutes a version change.

I am not familiar with the various tools used to generate all of the
scripts so I can't comment on the remaining changes.  However, they all
seem to be related to changes over time to the various tools (parameter
names etc.) so they look reasonable.

BTW, I don't think the generated Makefile actually builds the Doxygen
documentation for CppTest.

Thanks

Shalom

**Comment by hartwork** [comment]
>  [..]  so they look reasonable.

Okay cool!

> BTW, I don't think the generated Makefile actually builds the Doxygen documentation for CppTest.

Have you tried `--enable-doc`? `./configure --enable-doc && make` works for me. We can consider flipping the default to "enabled".

**Comment by reichs** [comment]
That seems to work for the documentation.  As I mentioned, I am really not
up on the build/install tools.  Thanks for pointing it out.

Shalom

**Comment by hartwork** [comment]
I have merged #10 to master now and bumped the version to 2.0.0 on top, following semver.
Before a release, the minimum needed more would be:
- Understand and/or fix Doxygen issue #11 
- Understand and/or fix memleak #2 
- Extend the changelog for #9 and version 2.0.0

If you can help with any of that, that would be welcome.

**Comment by reichs** [comment]
Is there a reproducible test case for the mem leak?  If not, there is no
documentation in the ticket on how to reproduce the problem.  Perhaps
running valgrind to run the mytest test cases?

Adding the configure option to ./configure worked for #11.  So I don't
think any more needs to be done.

Thanks

Shalom

**Comment by reichs** [comment]
The only possible mem leak that I see in mytest.cpp is that the variable
named "output" is a raw pointer up to the last line of the cmdline()
function that isn't being deleted in the case where --usage is supplied on
the command line (line 192).  It could be changed to a
unique_ptr<Test::Output> right on line 174.  No need to assign it 0.  IIRC,
unique_ptr will initialize to null if no pointer is passed to the ctor.

Shalom

**Comment by hartwork** [comment]
> that isn't being deleted in the case where --usage is supplied on the command line (line 192)

`output` is still at `0` in that case. I see no leak there.

> Perhaps running valgrind to run the mytest test cases?

I'm working on integration of AddressSanitizer right now on branch `asan` (https://travis-ci.org/cpptest/cpptest/builds)

**Comment by hartwork** [comment]
@reichs I have released 2.0.0 just now. Please give it a spin and open new tickets for things that seem out of line. Thanks!
